---
title: "Processing GSE147405 scRNASeq data for integration with COBRA"
author: "Scott Campit"
output: html_notebook
---
  
# Summary
This notebook processes scRNASeq time course data. Some of the code was adapted from Cook et al., 2020.

# Download all dependencies

First, we'll download several dependencies for data processing and data visualization.

```{r, include=FALSE}
pkgLst = c("Seurat", "dplyr", "viridis", 
           "matrixStats", "UpSetR", 
           "mgcv", "tidyverse", "reshape2", "ggplot2")
install.packages(pkgLst)

library(mgcv)
library(splines)
library(Seurat)
library(dplyr)
library(tidyr)
library(viridis)
library(matrixStats)
library(UpSetR)
library(reshape2)
library(ggplot2)
```

# Pseudotime analysis

```{r, include=FALSE}
plot_data <- a549@meta.data
plot_data$UMAP1 <- Embeddings(a549, "umap_pseudo")[,1]
plot_data$UMAP2 <- Embeddings(a549, "umap_pseudo")[,2]

```

```{r, include=FALSE}
PRGn <- rev(RColorBrewer::brewer.pal(11, "PRGn"))
color_ramp <- c(PRGn[1], PRGn[2], PRGn[3], PRGn[4], "grey50", PRGn[7], PRGn[8], PRGn[9])
```


```{r, include=FALSE}
# Actual time points
timepoint_plot <- ggplot(plot_data, aes(x=UMAP1, y=UMAP2)) +
  geom_point(size=2, alpha=0.75, aes(color=Sample),
             shape=16) +
  scale_color_manual(values=color_ramp) +
  theme_void() +
  theme(legend.position="none")

# Pseudotime
pseudo_plot <- ggplot(plot_data, aes(x=UMAP1, y=UMAP2)) +
  geom_point(size=2, alpha=0.75, aes(color=Pseudotime),
             shape=16) +
  scale_color_viridis(option="D") +
  theme_void() +
  theme(legend.title=element_blank(),
        legend.text=element_blank())
```

```{r, include=FALSE}
timepoint_plS

```{r, include=FALSE}
mlt <- melt(exp)
ggplot(data = mlt, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()
```